[package]
name = "flkv"
version = "0.1.0"
edition = "2018"


[lib]
name = "flkv"
crate-type = ["cdylib", "staticlib"]


[dependencies]
rusty-leveldb = "1.0.4"

[build-dependencies]
cbindgen = "0.24.3"

[profile.release]
opt-level = 'z'
panic = 'abort'
lto = true
codegen-units = 1
