#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.49.0.

use crate::flutter_bridge::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;

// Section: imports

// Section: wire functions

fn wire_open_impl(
    port_: MessagePort,
    path: impl Wire2Api<String> + UnwindSafe,
    in_memory: impl Wire2Api<bool> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "open",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_path = path.wire2api();
            let api_in_memory = in_memory.wire2api();
            move |task_callback| Ok(open(api_path, api_in_memory))
        },
    )
}
fn wire_close_impl(port_: MessagePort, db: impl Wire2Api<String> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "close",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_db = db.wire2api();
            move |task_callback| Ok(close(api_db))
        },
    )
}
fn wire_get_rows_impl(port_: MessagePort, db: impl Wire2Api<String> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_rows",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_db = db.wire2api();
            move |task_callback| Ok(get_rows(api_db))
        },
    )
}
fn wire_get_impl(
    port_: MessagePort,
    db: impl Wire2Api<String> + UnwindSafe,
    key: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_db = db.wire2api();
            let api_key = key.wire2api();
            move |task_callback| Ok(get(api_db, api_key))
        },
    )
}
fn wire_put_impl(
    port_: MessagePort,
    db: impl Wire2Api<String> + UnwindSafe,
    key: impl Wire2Api<String> + UnwindSafe,
    value: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "put",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_db = db.wire2api();
            let api_key = key.wire2api();
            let api_value = value.wire2api();
            move |task_callback| Ok(put(api_db, api_key, api_value))
        },
    )
}
fn wire_delete_impl(
    port_: MessagePort,
    db: impl Wire2Api<String> + UnwindSafe,
    key: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "delete",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_db = db.wire2api();
            let api_key = key.wire2api();
            move |task_callback| Ok(delete(api_db, api_key))
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<bool> for bool {
    fn wire2api(self) -> bool {
        self
    }
}
impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

impl support::IntoDart for Row {
    fn into_dart(self) -> support::DartAbi {
        vec![self.key.into_dart(), self.value.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Row {}

impl support::IntoDart for Rows {
    fn into_dart(self) -> support::DartAbi {
        vec![self.rows.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Rows {}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
